### ISSUE TITLE
Bootstrap v4 Support?

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#100]
Is bootstrap v4 supported through the bootstrap-loader?

I included it via direct include inside my app.style.scss, but I think that's not the right way...

**Comment by qdouble** [comment]
Great, glad you figured it out 😄 👍

**Comment by smith64fx** [comment]
Unfortunately it doesn't work with AoT..

AoT is compiling fine but the bootstrap css is not loaded :/

**Comment by qdouble** [comment]
@smith64fx I have a branch with bootstrap 4 and ng-bootstrap, but the aot is currently working correct, but the ng-bootstrap team is working on it. I'll update that branch when ever that's working right.

**Comment by smith64fx** [comment]
Hey @qdouble 
I looked at your bootstrap branch. 
I realized we don't need to use the bootstrap-loader as I did.

Just as simple as you did:

```
@import 'variables';
@import 'bootstrap/scss/bootstrap.scss';
```

Works fine :)
Now the website is really fast! Thank you so much!

I hope the problem with ng-bootstrap will be fixed soon, then everything will be awesome !!
