### ISSUE TITLE
Using Bootstrap 3, my take

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular2webpack2-starter#103]
I need to use Bootstrap 3 in my test app which is based on the **minimal** branch. So, these are my changes:

1. npm install bootstrap-loader
2. npm install jquery --save-dev
3. npm install bootstrap-sass css-to-string-loader extract-text-webpack-plugin@2.0.0-beta.4 file-loader sass-loader style-loader url-loader --save-dev

**constant.ts:**
```
const ProvidePlugin = require('webpack/lib/ProvidePlugin');

exports.MY_CLIENT_PLUGINS = [
  // use this to import your own webpack config Client plugins.
   new ProvidePlugin({
            jQuery: 'jquery',
            $: 'jquery',
            jquery: 'jquery',
            "Tether": 'tether',
            "window.Tether": "tether"
        })

]
```

**main.browser.ts**:
```
import 'jquery';
import 'bootstrap-loader';
```

**app.component.html** (just to see if Bootstrap works):
```
<header>
	<h1>Angular Starter App</h1>
	<ul id="my-navlist">
		<li *ngFor="let view of views">
			<a [routerLink]="view.link" routerLinkActive="active-link">{{view.name}}</a>
		</li>
	</ul>
</header>
<div class="container">
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1"
					aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
				<a class="navbar-brand" href="#">Brand</a>
			</div>

			<!-- Collect the nav links, forms, and other content for toggling -->
			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li class="active"><a href="#">Link <span class="sr-only">(current)</span></a></li>
					<li><a href="#">Link</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Separated link</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">One more separated link</a></li>
						</ul>
					</li>
				</ul>
				<!--<form class="navbar-form navbar-left">
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Search">
					</div>
					<button type="submit" class="btn btn-default">Submit</button>
				</form>-->
				<ul class="nav navbar-nav navbar-right">
					<li><a href="#">Link</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
						<ul class="dropdown-menu">
							<li><a href="#">Action</a></li>
							<li><a href="#">Another action</a></li>
							<li><a href="#">Something else here</a></li>
							<li role="separator" class="divider"></li>
							<li><a href="#">Separated link</a></li>
						</ul>
					</li>
				</ul>
			</div>
			<!-- /.navbar-collapse -->
		</div>
		<!-- /.container-fluid -->
	</nav>
	<main>
		<router-outlet (activate)="activateEvent($event)" (deactivate)="deactivateEvent($event)"></router-outlet>
	</main>
</div>
```
**rename app.component.css to app.component.scss** and add this import:
```
@import "~bootstrap-sass/assets/stylesheets/bootstrap";
```

**app.component.ts** - change accordingly:
```
  styleUrls: ['./app.component.scss'],
```

**webpack.config.ts** - add loaders:
```
      {
        test: /\.(sass|scss)$/,
        loaders: ['css-to-string-loader', 'css-loader?sourceMap', 'resolve-url', 'sass-loader?sourceMap']
      },
      { test: /\.woff(2)?(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'url?limit=10000&minetype=application/font-woff' },
      { test: /\.(ttf|eot|svg)(\?v=[0-9]\.[0-9]\.[0-9])?$/, loader: 'file' },
```

Now, since I'm not even close to webpack (and AOT, DLLs, etc) expert, my question - is this correct approach? I see that it works in dev and prod, haven't tried AOT yet.

Can we have a separate branch for Bootstrap 3? I may try to use ng2-bootstrap later..

**Comment by qdouble** [comment]
@alvipeo well directly using scss instead of scss will make AOT compile fail, which on the Other branches you will see I'm css for the styles URL but working with scss that is being converted with node-sass...(this issue will change once we can use the ngtools/webpack plugin). Beyond that, I suppose using JQuery at all may make it problematic to use Universal...not quite sure about AOT.

I'm not going to make a Bootstrap 3/Jquery branch as I think it's generally recommended to avoid using JQuery as you're probably going to run into a ton of issue when it comes to Universal, Web Workers and possibly AOT. I was working on a boostrap 4 branch that uses ng2-bootstrap, but they currently have an issue with AOT (which should be solved eventually).

**Comment by alvipeo** [comment]
Well, some people do not need Universal, that's why I used minimal branch.

I'd go for a Bootstrap 4, but it seems like its alpha state is never ending story, so I'll skip. ng2-bootstrap looks good, I'm going to try it.

Didn't get what you said about scss... at all ;)

**Comment by qdouble** [comment]
@alvipeo well of course, some people won't need to use Universal or Web Workers and maybe won't use AOT, but as using JQuery can be very problematic and limiting, I rather not create a branch based around using it. 

As far as scss, the ngc compiler does not support or understand sass...so using it in your styles url will cause AOT compilation to fail. In the other branches, you'll see that I mitigate this by compiling the scss using node-sass and referencing the css that is output in the stylesUrl array. There is going to be a webpack plugin for AOT that will get around this, but it's not available for public use yet.

**Comment by alvipeo** [comment]
ok, thanks. I'd pass Bootstrap, but what are options? Bootstrap 4 is not even close to ready, Material is not going to be even at beta by the end of the year... so how would one make a web ui really? This I think is the main reason people use React.

**Comment by qdouble** [comment]
@alvipeo If you're just using Bootstrap 4 for it's css, I wouldn't worry about it as the api for that is pretty stable. Combine that with ng2-bootstrap which should become AOT compatible soon, and you're golden.

**Comment by DzmitryShylovich** [comment]
ng-bootstrap*
and it's already aot ready

**Comment by qdouble** [comment]
@DzmitryShylovich yeah, ng-bootstrap is the correct repo 😄 

so this issue should be closed now? https://github.com/ng-bootstrap/ng-bootstrap/issues/796

**Comment by DzmitryShylovich** [comment]
Hmm I thought it work in aot. My bad.

**Comment by qdouble** [comment]
@DzmitryShylovich yeah, it still doesn't appear to work just yet, it's not exporting all of the .ngfactory files that it needs to

I just added the bootstrap branch I was working on locally... whenever they fix AOT on ng-bootstrap, I'll add the fix there

**Comment by alvipeo** [comment]
wow! Thanks you guys for Bootstrap 4 branch!
