### ISSUE TITLE
Feature request: Preload lazy loaded bundles

### ISSUE THREAD

**Issue by DzmitryShylovich** [qdouble/angular2webpack2-starter#104]
https://www.softwarearchitekt.at/post/2016/10/02/optimizing-performance-with-preloading-and-the-new-angular-router.aspx

**Comment by qdouble** [comment]
@DzmitryShylovich the article suggests those features will be available on router 3.1.0, but the current latest router version appears to be 3.0.2 and those modules are not available on it. I suppose it's only available if we use the nightly builds of router.

**Comment by DzmitryShylovich** [comment]
Yeah https://github.com/manfredsteyer/preloading-angular-2/blob/master/package.json#L53

**Comment by qdouble** [comment]
ah ok, will install it and see if it seems stable

**Comment by DzmitryShylovich** [comment]
afaik there should be no breaking changes

**Comment by qdouble** [comment]
@DzmitryShylovich had remove this from starter until AOT bug is fixed: https://github.com/angular/angular/issues/12141
