### ISSUE TITLE
Module not found error in dll polyfill during run command of "build:dll"

### ISSUE THREAD

**Issue by echo8795** [qdouble/angular2webpack2-starter#105]
face these errors during script run of "build:dll"

ERROR in dll polyfill
Module not found: Error: Can't resolve 'sockjs-client' in '/home/crucible/Programming/angular2webpack2-starter-master'
 @ dll polyfill

ERROR in dll polyfill
Module not found: Error: Can't resolve 'querystring-es3' in '/home/crucible/Programming/angular2webpack2-starter-master'
 @ dll polyfill

ERROR in dll polyfill
Module not found: Error: Can't resolve 'strip-ansi' in '/home/crucible/Programming/angular2webpack2-starter-master'
 @ dll polyfill

**Comment by qdouble** [comment]
it seems you're missing dependencies, did you run npm install on a fresh clone?

**Comment by qdouble** [comment]
I can't reproduce this error...if you do a fresh clone and install and still see this issue then let me know.

**Comment by echo8795** [comment]
Yeah i did a fresh clone and installed again. Worked. Thanks. Awesome repo.
