### ISSUE TITLE
'.' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by DzmitryShylovich** [qdouble/angular2webpack2-starter#11]
[This change](https://github.com/qdouble/angular2webpack2-starter/commit/4ce8abc5cc377a5556c8e13ff7a0501d19869f80#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R15) introduced a bug for windows users. 

`"ngc": "\"./node_modules/.bin/ngc\" -p src && npm run rimraf -- output",` throws `'.' is not recognized as an internal or external command` error.

It should be `"ngc": "./node_modules/.bin/ngc -p src && npm run rimraf -- output",`.

**Comment by qdouble** [comment]
@DzmitryShylovich thanks, I just updated it.
