### ISSUE TITLE
Can't npm install - getting 504

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular2webpack2-starter#114]
That's weird - I've been trying to 'npm install' this repo for hours and I get 504 when it tries to fetch
>> fetchMetadata: sill mapToRegistry uri https://registry.npmjs.org/webpack-dev-middleware

I tried on another machine - same thing. Does anybody know what does it mean? It worked flawlessly yesterday...

**Comment by prijindal** [comment]
I think there is some problem with npm modules
replacing
``` "angular2-router-loader": "~0.3.0"```
to
``` "angular2-router-loader": "0.3.0"```
in package.json fixed that problem

**Comment by qdouble** [comment]
Yeah, something seems to be wrong with that npm, I'll lock it on 0.3.0 for now: https://github.com/qdouble/angular2webpack2-starter/commit/6b4ddf5bda3665dc86909633f3a4ec129283f02b
