### ISSUE TITLE
Align with angular2 style guide

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#13]
@qdouble This is one of the best angular2 seeds out there. Thank you. Any chance we can align this to follow the style guide. I am happy to raise a PR if you don't have time but OK with the idea.

Feel free to close it if you don't like the idea.

**Comment by qdouble** [comment]
Sure, mostly in need to align to the naming conventions? I'm fine with aligning to it as long as we don't enforce the names in the lint.

**Comment by qdouble** [comment]
@mmrath this should be handled with: https://github.com/qdouble/angular2webpack2-starter/commit/e7060ea5dce37b95f28e3b35c7ee65665f9960be
and: https://github.com/qdouble/angular2webpack2-starter/commit/92659b0ff684689e4605191b9254ac32cfdedc1b
