### ISSUE TITLE
Question: Use of mdl css in index.html

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#14]
@qdouble What is the use of mdl css in index.html. As we use material2 I think we don't need the mdl css.

**Comment by qdouble** [comment]
@mmrath In a real project, I would currently use mdl for tables and layout as those probably won't be available in md2 for a while (it's not at the top of the agenda)... probably could remove from starter or show an example, not sure what's best. One main goal of the starter for me is to have it where you don't need to add on much more to build production.

**Comment by qdouble** [comment]
@mmrath I'm going to remove it, but I'm going to wait for material alpha 9 to come out as I'll be making some style updates when they release the theming support.

**Comment by qdouble** [comment]
@mmrath  closing this for now. I will remove it whenver theming support is added to md2 and md-input is working properly with Universal. I'll ping you when that happens.
