### ISSUE TITLE
Feature: Universal Support

### ISSUE THREAD

**Issue by mclouvem** [qdouble/angular2webpack2-starter#15]
Hi @qdouble,

Now with Angular 2.0.0 and Angular Universal 2.0.0 is out, is there any plan to add it to this kit?

Or could you provide some guidance how to make it?

**Comment by qdouble** [comment]
@mclouvem I will probably add it soon, I was just waiting for it to be stable. I will test it out today.

**Comment by qdouble** [comment]
@mclouvem I started the setup for it, but I hit a bump in the road for now.... Material Design 2 doesn't currently work with Universal, so that support needs to be added for me add Universal to this repo.

You can track the issue here: https://github.com/angular/material2/issues/308

**Comment by mclouvem** [comment]
hey @qdouble did you read that Patrick from AngularUniversal announced that AngularUniversal is now supporting Material2?

**Comment by qdouble** [comment]
@mclouvem yes, it's more or less a webpack hack though rather than native support. I have it running, but seems to be some issues with md-input. I'll release initial implementation of it tonight though, I already have it up and running, just making tweaks and stuff.

**Comment by qdouble** [comment]
@mclouvem I just added the basic setup for Universal. Currently, there is still an issue with md-input so I'm not using it in the repo right now. I still need to add support for AOT mode while using Universal and also look into using preboot and stuff like that so values that are entered before full load are saved. It's a WIP but the basic framework is there and I've tried to lay it the project in a way where I can update it and you could easily just insert your app folder to the updated seed.

**Comment by mclouvem** [comment]
@qdouble that's great! Thank you it was quick... I'll update my project today.
Could you explain more about what's wrong with md-input?

**Comment by qdouble** [comment]
It causes universal to have a circular JSON error. Should work smooth once
material officially supports Universal though.

**Comment by qdouble** [comment]
@mclouvem closing this as preboot runs fine, so Universal itself is working good. I'll ping you whenever the md-input thing is sorted out.

**Comment by qdouble** [comment]
@mclouvem was talking with going back and forward with patrick in Slack and got him to fix the md-input bug in the latest update, so it's working fine now 😄

**Comment by mclouvem** [comment]
Thanks again @qdouble. You're working hard on this starter...
