### ISSUE TITLE
app.css missing

### ISSUE THREAD

**Issue by jennyraj** [qdouble/angular2webpack2-starter#2]
Module not found: Error: Can't resolve './app.css' in 'E:\Temp_delete\angular2webpack2-starter\src\app'
 @ ./src/app/app.ts 40:21-41
 @ ./src/app/app.module.ts
 @ ./src/main.browser.ts
 @ multi main

Renamed app.scss to app.css and works fine!

**Comment by qdouble** [comment]
If you run 'npm run sass' it will compile it and most of the scripts should compile it. When I get back in front my computer, I'll update it to do it on install and make sure all the scripts compile it when ran.

**Comment by qdouble** [comment]
@jennyraj I updated the postinstall script to run `npm run scss` postinstall and I updated the readme.

**Comment by jennyraj** [comment]
thank you !!
