### ISSUE TITLE
Some warnings on app start

### ISSUE THREAD

**Issue by mclouvem** [qdouble/angular2webpack2-starter#40]
Hi @qdouble. I've just cloned the repo again, installed deps and ran `npm start`. There are some warning on bundle verification. Please check out the image.

![starter_error](https://cloud.githubusercontent.com/assets/1014444/18722074/b1df46f2-8009-11e6-946b-a13609f57143.PNG)

**Comment by qdouble** [comment]
@mclouvem seems your install isn't picking up @types/protractor which is weird because it's in the package.json. Can you uninstall and reinstall it? May be some typescript flakiness.

**Comment by qdouble** [comment]
@mclouvem also, see if pinning @types/protractor to version 1.5.18 makes a differences

**Comment by mclouvem** [comment]
@qdouble I've changed package.json like this: "@types/protractor": "1.5.18", cleaned npm cache and ran npm install and I got the same errors (on linux)
On windows 10 I tried to run it and I got this error:
 `throw new TSError(diagnosticList)
                ^
TSError: ⨯ Unable to compile TypeScript
webpack.config.ts (19,5): Cannot find name 'require'. (2304)`

**Comment by qdouble** [comment]
@mclouvem okay, will hunt down the first issue and then pin down the version numbers, seems like the package authors are introducing breaking changes every other day

**Comment by qdouble** [comment]
@mclouvem the original issue should be fixed with this: https://github.com/qdouble/angular2webpack2-starter/pull/42/files

looking into the Windows issue now

**Comment by qdouble** [comment]
@mclouvem @DzmitryShylovich I was testing on VM...I set the tsconfig to be able to work on Windows here: https://github.com/qdouble/angular2webpack2-starter/pull/43/files 

I see a couple of duplicate identifier warnings but it runs. Whether or not it works well for you or you know a way to get it set even better, let me know.

**Comment by qdouble** [comment]
@mclouvem @DzmitryShylovich: It should be fully fixed with this commit: https://github.com/qdouble/angular2webpack2-starter/pull/44 . I'll start testing updates on VM for Windows, so hopefully it should stay running well.

**Comment by mclouvem** [comment]
Perfect @qdouble, I tested on linux and win10 and it worked perfectly in both systems.

Thanks man! your support is amazing...
