### ISSUE TITLE
npm run test fails with node v4

### ISSUE THREAD

**Issue by isaacplmann** [qdouble/angular2webpack2-starter#41]
`npm run test` throws an error:

`SyntaxError: Unexpected token ...`

It says the error is happening at `/config/karma.conf.js:9:27` but I'm pretty sure the culprit is inside the required file at `/config/webpack.test.js:143:7`.

I'm running node version 4.2.6, which might be causing the issue.  Perhaps this is just a documentation bug.

**Comment by isaacplmann** [comment]
Just verified that everything works fine with node 6.x

**Comment by qdouble** [comment]
@isaacplmann I updated the packages a bit earlier, let me know if there is a still an issue, I'll update the readme if so.
