### ISSUE TITLE
instructions to remove Universal support

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#46]
@qdouble Would you have time to quickly write some notes around how to remove Universal support? Looks like there is no support for Universal in Java World, so I'll not use that functionality in near future, so I don't want to download the deps and  maintain the related config.

**Comment by qdouble** [comment]
@mmrath sure, I've added link to non-universal branch in the starter: https://github.com/qdouble/angular2webpack2-starter/pull/48

**Comment by mmrath** [comment]
@qdouble Awesome! Can't thank you enough for your work on this repo.
