### ISSUE TITLE
Move e2e test files to top level 

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#47]
It would be good to move the e2e test files to a folder named e2e at the same level as src. Because e2e spec are not specific to a component, it does not look clean to keep them aside component file.

**Comment by qdouble** [comment]
I think it's useful to have e2e tests near to the features you are testing and I see it put that way in most starter and sample apps. I'll leave that the way it is as it shouldn't be too difficult for a person to to move it if they want to.

**Comment by qdouble** [comment]
@mmrath After checking how Angular itself is doing it on their repo, I've decided to go with your suggestion: https://github.com/qdouble/angular2webpack2-starter/pull/49 and on the non universal branch: https://github.com/qdouble/angular2webpack2-starter/commit/e9cd2b5bd4326634bd72c38b4f5c15a2905b9b9b
