### ISSUE TITLE
CSS/SCSS

### ISSUE THREAD

**Issue by Tempus35** [qdouble/angular2webpack2-starter#51]
Seems the minimal branch is missing the commands/files for the css and scss.

**Comment by qdouble** [comment]
I removed scss from the minimal branch, but forgot to take .gitignore off of css. That should be added back here: https://github.com/qdouble/angular2webpack2-starter/commit/df6ee8b71138cde99d19cfcd84b2553a577f1001. Let me know if there are any issues with it now.
