### ISSUE TITLE
Universal Issues

### ISSUE THREAD

**Issue by Tempus35** [qdouble/angular2webpack2-starter#52]
Running the app in universal mode via npm run universal and going to localhost:8000 does not seem to fully work. It seems to load the page but any click on the page adds a grey overlay and does nothing after.

**Comment by qdouble** [comment]
@Tempus35 can you share what error you are getting on the console if any? Also, make sure to run `npm i` or `npm run clean && npm run i` when switching between branches to make sure all of the dependencies are loaded up properly.

**Comment by qdouble** [comment]
@Tempus35 nevermind, I see it...hunting down the issue now... probably either something with the polyfills or zone.js

**Comment by qdouble** [comment]
@Tempus35 it should be fixed with this commit: https://github.com/qdouble/angular2webpack2-starter/commit/c1e00fd9bcd50a78e750ded9423981d49c346062
