### ISSUE TITLE
Support optional proxy to backend

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#59]
It would be nice to be able to use a real backend api during development. May not be useful always,  but certainly useful times.

**Comment by qdouble** [comment]
@mmrath can you give me more details of what type of implementation you are thinking about? Typically, when I'm developing... I have a node server in separate process that I'm interacting with but I'm using it for prod server anyway... would it just be something like that or different?

**Comment by Matmo10** [comment]
For example, I have a java/spring backend running on localhost:8080. My UI is served on localhost:3000. I can't hit my backend API's without a proxy.

**Comment by qdouble** [comment]
@mmrath me, I'd typically deal with constants variable...but Webpack does devServer does have proxy option, I will look into adding it.

**Comment by mmrath** [comment]
@qdouble yes I cureently modify devserver to add proxy option. It would be nice to put that in constants or somewhere as config

**Comment by qdouble** [comment]
@mmrath will do

**Comment by qdouble** [comment]
@mmrath @Matmo10 it's added with this pull request: https://github.com/qdouble/angular2webpack2-starter/pull/61, just set it in constant.js file:
