### ISSUE TITLE
HMR support

### ISSUE THREAD

**Issue by mclouvem** [qdouble/angular2webpack2-starter#6]
I've just started to use your starter kit; and it is awesome.

I saw that on every change the page is reloaded. So I'd like to ask you about HMR support. Is it possible to add it using webpack2/Tree Shaking/AOT?

**Comment by qdouble** [comment]
@mclouvem Hey, glad you like the kit. I may add HMR support when I see a good implementation of it that works with current stuff... however, you would probably only be able to use it in JIT dev mode, not while you are using AOT, as AOT requires a compile step that's totally different form the build/watch step.

**Comment by mclouvem** [comment]
@qdouble Yes, I really liked the kit you put together! Congrats and thanks again

Yes, It'd be used only in JIT mode. Sorry for ask, but what kind of problem do you see on AngularClass implementation of HMR?

**Comment by qdouble** [comment]
@mclouvem I'm more of a fan of @ngrx/store for state management and I'm hoping for an HMR implementation of that which will work for rc5/rc6... there was one that worked before ngModules. I'll probably hold off for a week or two to see if any development happens on that front, then look more towards the AngularClass way if not.

**Comment by mclouvem** [comment]
@qdouble good to know about that. Just one more question before close this issue: is there any reason to not integrate ngrx/store inside this kit? I'm planning to use it on my project, so do you have some trips about how to better structure the app?

**Comment by qdouble** [comment]
@mclouvem well there is a wide range of opinions of exactly how much stuff should be put into a starter kit and I'm not necessarily trying to overload it, but if I use it for hmr support, then that will be a good excuse for me to put it in there. There's a good example app for ngrx on that repo, but the example app update for rc6/aot is a work in progress. NgModules and AOT are fairly new so best practices haven't been established yet.

**Comment by mclouvem** [comment]
@qdouble by "that repo" do you mean ngrx/store repo?

**Comment by qdouble** [comment]
yeah, here's a direct link to what I'm referring to: https://github.com/ngrx/example-app/pull/43
