### ISSUE TITLE
tsconfig.aot.json/any advice you could give?

### ISSUE THREAD

**Issue by tomgeorge** [qdouble/angular2webpack2-starter#64]
Hi, 

I was wondering why you don't have the "module": "es2015" option on your tsconfig.aot.json?  Also, why do you have an explicit typeRoots instead of the "types" array?

I've got a [fork](https://github.com/tomgeorge/angular2-starter-webpack) of the AngularClass repo that I'm trying to get working.  I have it modeled after your repo as well.  When i try to run ngc I get this message:

```
can't resolve module @angular/core/src/di/metadata from C:\Users\Tom\git\angular2-webpack-starter\index.ts
Error: can't find symbol Host exported from module C:/Users/Tom/git/angular2-webpack-starter/node_modules/@angular/core/src/di/metadata.d.ts
    at ReflectorHost.findDeclaration (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\reflector_host.js:173:23)
    at StaticReflector.initializeConversionMap (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\static_reflector.js:147:55)
    at new StaticReflector (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\static_reflector.js:42:14)
    at Function.CodeGenerator.create (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\codegen.js:142:31)
    at codegen (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\main.js:7:36)
    at Object.main (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\tsc-wrapped\src\main.js:30:16)
    at Object.<anonymous> (C:\Users\Tom\git\angular2-webpack-starter\node_modules\@angular\compiler-cli\src\main.js:14:9)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
Compilation failed
```

When I change both `"target"` and `"module"` to `"es2015"`, I get further, I think, messages about being unable to resolve stuff like `@angular/router`, etc.  The furthest I've gotten is getting it to compile into `output/`, but it won't generate factory classes.

Curiously, when I add `"moduleResolution": "node"`, I go back to square 1 above.

Is there any chance you could take a look at my fork and see if anything obvious jumps out at you?  The only other examples of working AoT are super minimal.  

`git clone https://github.com/tomgeorge/angular2-webpack-starter`
`git checkout -b aot && git pull origin aot`
`npm install`
`npm run ngc`

**Comment by DzmitryShylovich** [comment]
> why you don't have the "module": "es2015" option on your tsconfig.aot.json?

this's required for Rollup as explained [here](https://angular.io/docs/ts/latest/cookbook/aot-compiler.html#!#tree-shaking). We use webpack treeshaking capabilities in this repo.

> why do you have an explicit typeRoots instead of the "types" array?

both `types` and `typeRoots` are redundant with the latest tsc.

**Comment by qdouble** [comment]
@tomgeorge @DzmitryShylovich  I'm only using typeRoots as it improves the compatibility on Windows (seems like TS or ts-node bug), It's not necessary outside of that.

The AngularClass repo is using default exports and possibly other bad practices for working with AOT, it would be for you to just switch to using my repo, it would take me a lot of time to refactor their repo, which I have no desire to do.

**Comment by tomgeorge** [comment]
@qdouble @DzmitryShylovich   Thanks for the response.  

Sorry if I was unclear, I'm not asking you to refactor their repo, I was just wondering if anything jumped out at you immediately (e.g. removing default exports).  I'll do that, and try to model after your repo.  I could just fork yours and get going, but I'd like to get a little more understanding/get my hands dirty.

Could you recommend any resources that helped you get your repo going?  I'm relatively new to js/ts, so stuff like when to use `libs` in `tsconfig.json`, core-js vs es6-shim, what the point of default exports is, etc.

Obviously, I have been/am googling stuff on my own, just if you know of anything off the top.

**Comment by qdouble** [comment]
@tomgeorge follow the AOT don'ts: https://github.com/qdouble/angular2webpack2-starter#aot--donts. There could be other configuration concerns as far as the webpack build itself, but that's a bit of a troubleshooting task.

My experience basically came from tinkering with different starter repos and just learning what does what over time. Probably best to just choose a starter at first then try to modify it for your purposes. Once you start to know enough, then you should be able to make your own build from scratch...but it took me months before I started to fully grasp webpack, so don't be worried about understanding it all over night.

**Comment by tomgeorge** [comment]
I'm pretty happy with my webpack setup right now (using platform-browser-dynamic). But like you said, it took me months and months to get to where I am now.  Then I read about AoT and I was like "hey, I want to do that".  Hopefully I can piggyback on my webpack/ng2 experience :)

I'll keep tinkering with the angular2-webpack-starter.   Thanks again for your help.
