### ISSUE TITLE
npm fails when installing new packages

### ISSUE THREAD

**Issue by felipedrumond** [qdouble/angular2webpack2-starter#66]
when trying to install ANY npm package, such as lodash, jquery etc, the following error happens:

-> npm install lodash --save

> node-zopfli@1.4.0 install C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! **Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz**
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at failNoPython (C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\lib\configure.js:449:14)
gyp ERR! stack     at C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\lib\configure.js:404:11
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:123:15)
gyp ERR! System Windows_NT 10.0.14379
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=C:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14379
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=C:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
angular2webpack2-starter@0.1.0 C:\WORK\GraoDeGente\angular2webpack2-starter
+-- angular2-universal-polyfills@2.0.11
| `-- es6-promise@3.0.2
`-- lodash@4.16.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

Trying to get https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz by myself, the server returns 
`<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8E4BC6EA3B5AA488</RequestId>
<HostId>
BDlT4cmwVrwDQ6iU6fG3hCuzS9uI9z2y1gcEuu5bsexjeZrUsABWlRHXLU86/rbTElS5OFwjzfg=
</HostId>
</Error>`

**Comment by DzmitryShylovich** [comment]
> Can't find Python executable "python", you can set the PYTHON env variable.

You nee to install python. See https://github.com/nodejs/node-gyp#installation

**Comment by felipedrumond** [comment]
Hi @DzmitryShylovich, I tried that before and it got worse :-(
I tried once more following the link you mentioned, and the problem now is:

npm install lodash --save

> node-zopfli@1.4.0 install c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
> node-pre-gyp install --fallback-to-build

node-pre-gyp ERR! Tried to download: https://node-zopfli.s3.amazonaws.com/Release/zopfli-v1.4.0-node-v48-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for node-zopfli@1.4.0 and node@6.6.0 (node-v48 ABI) (falling back to source compile with node-gyp)
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [c:\WORK\GraoDeG
ente\angular2webpack2-starter\node_modules\node-zopfli\build\zopfli.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.14379
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-gyp\\bin\\node-gyp.js" "build" "--fallback-to-build" "--module=c:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64\\zopfli.node" "--module_name=zopfli" "--module_path=c:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-zopfli\\lib\\binding\\node-v48-win32-x64"
gyp ERR! cwd c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
gyp ERR! node -v v6.6.0
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:877:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.14379
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "c:\\WORK\\GraoDeGente\\angular2webpack2-starter\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli
node-pre-gyp ERR! node -v v6.6.0
node-pre-gyp ERR! node-pre-gyp -v v0.6.30
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64\zopfli.node --module_name=zopfli --module_path=c:\WORK\GraoDeGente\angular2webpack2-starter\node_modules\node-zopfli\lib\binding\node-v48-win32-x64' (1)
npm WARN install:node-zopfli@1.4.0 node-zopfli@1.4.0 install: `node-pre-gyp install --fallback-to-build`
npm WARN install:node-zopfli@1.4.0 Exit status 1
angular2webpack2-starter@0.1.0 c:\WORK\GraoDeGente\angular2webpack2-starter
`-- lodash@4.16.1

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14

**Comment by qdouble** [comment]
@felipedrumond I just tested on VM, doing this like on the link @DzmitryShylovich gave should solve the issue:

>Option 1: Install all the required tools and configurations using Microsoft's windows-build-tools using npm install --global --production windows-build-tools from an elevated PowerShell or CMD.exe (run as Administrator).

After that, then next time your run npm install, it should download the needed dependencies and be fine after that. Let me know if that doesn't solve it and I'll re-open.

**Comment by felipedrumond** [comment]
Hi @qdouble, it still throw errors. My environment is a VM with W10 Enteprise, VS 2015, Node 6.2.1.

C:\WORK\GraoDeGente\graoDeGenteApp>npm install rimraf

> timekit@1.0.3 install C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\timekit
> node-gyp rebuild


C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\timekit>if not defined npm_config_node_gyp (node "C:\Users\Felipe Drumond\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
**C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.
1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and
selecting "Retarget solution".** [C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\timekit\build\timekit.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Felipe Drumond\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Windows_NT 10.0.14379
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Felipe Drumond\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\timekit
gyp ERR! node -v v6.2.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

> v8tools@0.2.2 install C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\v8tools
> node-gyp rebuild


C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\v8tools>if not defined npm_config_node_gyp (node "C:\Users\Felipe Drumond\AppData\Roaming\npm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error MSB8036: The Windows SDK version 8.
1 was not found. Install the required version of Windows SDK or change the SDK version in the project property pages or by right-clicking the solution and
selecting "Retarget solution". [C:\WORK\GraoDeGente\graoDeGenteApp\node_modules\v8tools\build\v8tools.vcxproj]

**Comment by qdouble** [comment]
Have you tried to the do the retarget solution thing? I'm also demoed it using Windows 10 on VM (Parallels Desktop, if that makes any difference), and the `npm install --global --production windows-build-tools` and then running npm i again alone fixed it for me. You could also try to see if you can download and install the Windows SDK version it's stating in the error message.
