### ISSUE TITLE
Build issues on all other than npm start

### ISSUE THREAD

**Issue by patrickpereira** [qdouble/angular2webpack2-starter#68]
Hi!

Great project, I've done a fresh install on node 6.6, npm start is working, but if I use hot reload or prod, I get this:

<img width="677" alt="screen shot 2016-09-26 at 09 58 51" src="https://cloud.githubusercontent.com/assets/10369669/18824036/4bc9c98a-83d0-11e6-9443-a84dc4ddef07.png">

**Comment by Matmo10** [comment]
Are there any errors? It just looks like the material design styles are missing in that screenshot. Are you planning on keeping Material Design anyways? Does the hot reload / prod functionality work fine aside from the styling issues?

**Comment by qdouble** [comment]
If you look at the app.imports file you will see this 
```
// MdButtonModule, // Uncomment after initial load in HMR mode or before doing AOT compile
```
and then at the bottom this
```
/**
 * Currently, MdButtonModule stops HMR from working properly 
 * if it is imported on initial load. If you uncomment it after initial
 * load the page will refresh and MdButton will be fine.
 * If you find a better solution, please submit a PR or file an issue.
 */
if (!HMR) {
  APP_IMPORTS.push(MdButtonModule);
}
```

So basically, the MdButton is just being commented out so HMR keeps working... but you can always just uncomment it and things will work like normal. Also uncomment it if doing AOT render.

**Comment by patrickpereira** [comment]
ah wicked, thanks!
