### ISSUE TITLE
Question: Is there a way to generate css outside of main src folder?

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#7]
It is a bit confusing to when both css and scss present in the same folder

**Comment by qdouble** [comment]
@mmrath well the issue currently when trying to use AOT and sass, is that you can't directly use sass as styleUrls source, so if you generate the css to an outside folder, then you'll have to change that reference in the class metadata as well... doesn't seem to be an overly clean way to do it right now unless AOT supported Sass or didn't error on compile if you used it.
