### ISSUE TITLE
Cannot use @import '~bootstrap-sass/assets/stylesheets/bootstrap' Syntax

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#73]
Hey there,
First of all: Thanks for your awesome work :)

I try to import the bootstrap scss, but it doesn't work as it should.

app.scss
```
@import '~bootstrap-sass/assets/stylesheets/bootstrap';
```

I get this error

```
{
  "status": 1,
  "file": "/Users/smith/Git/test/src/app/app.style.scss",
  "line": 2,
  "column": 1,
  "message": "File to import not found or unreadable: ~bootstrap-sass/assets/stylesheets/bootstrap\nParent style sheet: /Users/smith/Git/test/src/app/app.style.scss",
  "formatted": "Error: File to import not found or unreadable: ~bootstrap-sass/assets/stylesheets/bootstrap\n       Parent style sheet: /Users/smith/Git/test/src/app/app.style.scss\n        on line 2 of src/app/app.style.scss\n>> @import '~bootstrap-sass/assets/stylesheets/bootstrap';\n   ^\n"
}
```

However: This works
```
@import '../../node_modules/bootstrap-sass/assets/stylesheets/bootstrap';
```

Well but this is not a good solution, because the location of my component can change. The ‘~/..' syntax worked fine in the angular2-webpack-starter (which I left for your starter ;-))

Maybe you have some idea :)

Thanks so much for this repo man!!
![image](https://cloud.githubusercontent.com/assets/3246782/18990198/ab62d52e-8710-11e6-934b-4299168ed0dd.png)

**Comment by qdouble** [comment]
@smith64fx It's a bit different because I'm using node-sass to compile the scss instead of webpack because of AOT...this may change when the @ngtools plugin is ready for public use. With this new PR https://github.com/qdouble/angular2webpack2-starter/pull/76, you should be able to use `@import 'bootstrap-sass/assets/stylesheets/bootstrap';`
