### ISSUE TITLE
HammerJS from npm

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#74]
@qdouble You think we can use HammerJS from npm instead of from CDN?

**Comment by qdouble** [comment]
@mmrath hammerjs accesses document and window, which could make it more problematic to use with Universal/Web Workers if you have it as a direct import into the project, although I suppose we could possibly copy it and still reference the file in the html...would there be big benefit here?

**Comment by alvipeo** [comment]
Just discovered this repo - wow! Thank you for it, going to start the new app with it!

On the topic - I just noticed hammer.js is loaded twice when running 'npm run server:prod' (probably dev too). Is there any reason for it?

**Comment by qdouble** [comment]
@alvipeo it's only there once as far as I can see, if it loaded twice, it was likely a cache issue

**Comment by alvipeo** [comment]
you're right - it was a cache issue. now it's gone.

**Comment by qdouble** [comment]
@mmrath Closing this issue as it's been changed to NPM with this commit: https://github.com/qdouble/angular2webpack2-starter/commit/e2cdcd5c9e559c07b68798c81a22bdc8e8483bad
