### ISSUE TITLE
Pug Support?

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#75]
Hi guys,
When I switched from the Angularclass Webpack Starter to this one, my .pug templates are still compiled but all the vowels etc. are not shown properly.

e.g.
äöä
becomes
Ã¼ÃœÃ¼

Before everything worked fine =/

I use the pug loader like this:
```
exports.MY_CLIENT_RULES = [
  { test: /\.pug$/, loader: 'pug-html-loader' },
]
```

Maybe is there some other workaround?
e.g. in the .scss files you also compile it first and include the .css files directly.

Maybe this is a stupid question sorry ^^

**Comment by smith64fx** [comment]
OK I solved it with another way!

Forget about this:
```
exports.MY_CLIENT_RULES = [
  { test: /\.pug$/, loader: 'pug-html-loader' },
]
```

To use pug in a very efficient way, try this:
```
 npm install pug --save-dev
```

Add this to your package.json
```
scripts: {
...
    "pug": "pug src/app",
    "pug:watch": "pug -w src/app src/app",
...
}
```

And add the pug:watch command to these lines 
```
    "server:aot": "npm-run-all -p -r webdev sass:watch pug:watch",
    "server:dev": "npm-run-all -p -r webdev sass:watch pug:watch",
    "server:hmr": "npm-run-all -p -r webdev:hmr sass:watch pug:watch",
    "watch:aot": "npm-run-all -p -r \"compile:watch -- --watch\" sass:watch pug:watch",
    "watch:dev": "npm-run-all -p -r \"build:dev -- --watch\" sass:watch pug:watch",
    "watch:prod": "npm-run-all -p -r \"build:prod -- --watch\" sass:watch pug:watch",
    "watch:universal": "npm-run-all -p -r \"build:universal -- --watch\" sass:watch pug:watch",
```

Include all your templates a normal .html, not as .pug
```
templateUrl: 'my.template.html',
```

I really like this pre-compiling stuff!

**Comment by qdouble** [comment]
Hey, glad you figured it out. Precompiling is probably the better way for now anyway because it would be more AOT safe...using a rule with `enforce: 'pre'` may be a solution once ngtools webpack plugin comes into place, but the current solution seems best for now.
