### ISSUE TITLE
Usage of Angular CLI

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#78]
Hey there,
Is it possible to use AngularCLI?

Sorry for opening an issue.. This question is maybe better for a chat like slack/gitter.

**Comment by DzmitryShylovich** [comment]
> This question is maybe better for a chat like slack/gitter.

you are right. it's not the best place to ask such questions.

both cli and custom webpack build have their pros and cons. there's no right answer for your question. you have to decide yourself.

**Comment by qdouble** [comment]
@smith64fx yeah, as @DzmitryShylovich said, there are pros and cons... I prefer to use Webpack as it gives me more customization options and CLI is still alpha/beta... but it's very dependent on what a person is using.
