### ISSUE TITLE
Material Design Lite

### ISSUE THREAD

**Issue by kodeine** [qdouble/angular2webpack2-starter#79]
I came across to [Material Design Lite](https://github.com/google/material-design-lite) what are your thoughts, maybe we can implement that in this package?

**Comment by qdouble** [comment]
@kodeine I was using it for some of it's css, but removed it from the starter. For it's css, you can just copy the cdn link into index.html or put it in assets folder and reference it. It's not really recommended to use it for it's javascript, unless you're using some third party implementation of it. No plans to add it to this repo though.
