### ISSUE TITLE
Non Internet applications

### ISSUE THREAD

**Issue by zigzag95** [qdouble/angular2webpack2-starter#80]
Please remove all Internet references from index.html since some applications may don't have access to Internet

**Comment by qdouble** [comment]
@zigzag95 I may remove some, but not sure about all (especially not the extra polyfills script as that would make certain browsers download more stuff unnecessarily)... and then it could also increase the amount browsers need to download for common files that would already be cached, like google fonts and icons. 

In the meantime, if you don't want any online dependencies, you could just put those files in the assets folder and reference that in index.html...or install as npm dependency.

**Comment by zigzag95** [comment]
No worry about extra downloads since webpack is doing a tree shaking.
I'll make a PR anyway.

**Comment by qdouble** [comment]
@zigzag95 most of those files are already minified and some shouldn't necessarily be packaged together... but if you make a pr, we can probably push it towards a strictly offline-friendly branch

**Comment by DzmitryShylovich** [comment]
> a strictly offline-friendly branch

do u really want to support one more branch? :)

**Comment by qdouble** [comment]
@DzmitryShylovich if it's a strict clone of this one minus the index.html files, it should be difficult to maintain... I'm conflicted on whether or not this current branch should have no CDN use, what's your opinion on this?

**Comment by qdouble** [comment]
@DzmitryShylovich yeah, I mean if someone wants to PR for it, I could see doing it..

as far as this main branch, I think getting hammer.js from npm may be a good thing... but I don't see a strong reason for most people to have a need to load google fonts and icons on their own server... and automatically loading extra safari/ie/edge polyfills isn't advantageous for Chrome/Firefox users, so CDN wins there too. As the main branches, I can only see a strong argument for hammerjs.

Now if we start transition towards the starter being for progressive apps, then all offline would make more sense as far as the main branches.
