### ISSUE TITLE
'rm' is not recognized as an internal or external command - Windows

### ISSUE THREAD

**Issue by alvipeo** [qdouble/angular2webpack2-starter#85]
Just cloned the repo on Windows 10 and run 'npm run build'. And got this:

>>'rm' is not recognized as an internal or external command

But it worked like 8 hours ago!

**Comment by qdouble** [comment]
@alvipeo will have it fixed soon, need to work out some kinks of some of the refactoring I was doing

**Comment by qdouble** [comment]
@alvipeo the issue should be fixed with this PR: https://github.com/qdouble/angular2webpack2-starter/pull/86

**Comment by alvipeo** [comment]
Thanks! I'm going to try to use this repo for Bootstrap 3.3.7. Let's see...

Best repo for ng2 to date!
