### ISSUE TITLE
Question: Usage of some of the libraries

### ISSUE THREAD

**Issue by mmrath** [qdouble/angular2webpack2-starter#93]
@qdouble for my knowledge, would you know the usage of the following libraries?

1.  "body-parser": "1.15.2"
2.  "compression": "1.6.2"
3.  "cookie-parser": "1.4.3"
4.  "express": "4.14.0"
5.  "methods": "1.1.2"
6.  "reflect-metadata": "0.1.8" (angular-cli does not use this, looks like not required with core-js)

Thanks
Murali

**Comment by qdouble** [comment]
Most of those are either for universal server or prod server. I think the
tests are using reflect-metadata, I'll have to double check if that's
necessary.

**Comment by mmrath** [comment]
I too thought most are for universal support. You think we can remove them from no-universal-support branch? I generally remove 1-5 after I copy your changes from no-universal-support branch

**Comment by qdouble** [comment]
Well express and compression are needed for prodserver, but I can probably
remove the other 3 off that branch. Then probably use core-js instead of
reflect-metadata on all branches.

**Comment by mmrath** [comment]
Should express and compression be dev dependencies if they are required for prod server?

**Comment by qdouble** [comment]
Well I'd consider them dependencies on the universal branch, but dev on the
other. It makes it easier for me to cherry-pick changes between branches to
keep them as similar as possible though.

**Comment by qdouble** [comment]
@mmrath your main issues should be taken care of with this commit: https://github.com/qdouble/angular2webpack2-starter/commit/8c30477c19fc480e50db92c1b750486167a475f5 and this PR: https://github.com/qdouble/angular2webpack2-starter/pull/94
