### ISSUE TITLE
npm run universal throws EXCEPTION: document is not defined

### ISSUE THREAD

**Issue by felipedrumond** [qdouble/angular2webpack2-starter#97]
I'm trying to run this repo as a universal app. The app runs on the client browser, but node console throws the following exception:

`[nodemon] starting `node dist/server/index.js`
Listening on: http://192.168.1.100:8000
EXCEPTION: document is not defined
ORIGINAL STACKTRACE:
ReferenceError: document is not defined
    at new RippleRenderer (C:\WORK\angular2webpack2-starter\node_modules\@angular\material\material.umd.js:193:31)
    at new MdRipple (C:\WORK\angular2webpack2-starter\node_modules\@angular\material\material.umd.js:327:32)
    at AppView._View_MdButton1.createInternal (MdButton.ngfactory.js:63:24)
    at AppView.create (C:\WORK\angular2webpack2-starter\node_modules\@angular\core\bundles\core.umd.js:9399:25)
    at TemplateRef_.createEmbeddedView (C:\WORK\angular2webpack2-starter\node_modules\@angular\core\bundles\core.umd.js:7487:18)`

Also, the html rendered by node is not complete - it does not have the target route html.

**Comment by qdouble** [comment]
@felipedrumond Hey, yes, Universal itself works fine, but Material alpha 9 is not fully Universal compatible (I've brought up the issue on their repo and on Slack)...nothing I can really do about that on this repo.

If you're in an early development phase, I wouldn't be worried about it too much as hopefully they will fix it soon... but if you need to be live anytime soon, the current options are to roll back to alpha 8-3 of Material or to not use Material.

**Comment by qdouble** [comment]
@felipedrumond If you want to rollback before the Universal/Material compatibility issue came up, you can run ` git checkout 607028da8b0`

I'll keep this issue open until either the Universal or Material team solve this issue.

**Comment by felipedrumond** [comment]
@qdouble thanks! It solved the problem when using universal. However, I'm trying to change the content of lazy.component.html, adding some html and a http request, but the compiler does not create the lazy.component.ngfactory.ts accordingly. It keeps your original version :-(

**Comment by qdouble** [comment]
@felipedrumond AOT should run fine. Are you running `npm run compile` ?

**Comment by qdouble** [comment]
@felipedrumond if you meant using Universal and AOT together, that's not currently possible, there are pending PR's and open issues on Universal repo, but AOT build should be fine with `npm run compile` and the using `npm run prodserver` or your own server.

**Comment by felipedrumond** [comment]
none of the options compile the changes I've made in lazy.component.html

I just tried npm run start, and the lazy rout still shows only "This module is being loaded lazily."

**Comment by qdouble** [comment]
@felipedrumond either you're doing something wrong or something is going wrong on your end, there's nothing in particular that should cause that should cause the html not to update. If you want me to investigate further, create a fork or or clone with you edits and tell me which commands you used so I can see the issue.

**Comment by qdouble** [comment]
@felipedrumond I'll close this one for now as the Material/Universal thing is not a problem in particular with this repo but an issue that either the material or universal team need to fix.  I've stated the current workarounds. I'll update the repo and ping you whenever they resolve those issues.
