### ISSUE TITLE
if/else/javascript logic inside index.html

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#98]
Hey guys,
Before I used AngularClass Webpack starter.

There, inside the index.html I could use a syntax like this:

```
<% if (webpackConfig.metadata.isDevServer || ENV === 'test' || ENV === 'local') { %> 
<!-- show some html based on the conditions above -->
<%= } %>
```

Unfortunately this syntax isn't working anymore =/

Do I have to include something or is there another syntax now?

Best Regards and 1000x thx for this awesome project!

smith

**Comment by qdouble** [comment]
Hey... Well for one, the index.html file is only loaded using the HTML plugin which allows such syntax in dev mode (as using this it in production is not possible with Universal and may also give you issues if you were to load up your dist files outside of Webpack). Beyond that, setting the metadata the way they did in on the other seed, will throw an invalid schema error in Webpack version 2.1.0-beta.25. 

You can look at the `<%= %>` code that is currently there in index.html. It will only be interpreted in dev mode.
