### ISSUE TITLE
Include ngrx-store-localstorage

### ISSUE THREAD

**Issue by smith64fx** [qdouble/angular2webpack2-starter#99]
Hi there :-)

I just tried to sync my state to the local storage, so after a page reload, I can reproduce the state from the local storage.

I used this plugin:
https://github.com/btroncone/ngrx-store-localstorage

What I tried is use the provideStore like this:
```
import { RouterStoreModule } from '@ngrx/router-store';
import { StoreModule, combineReducers } from '@ngrx/store';
import { compose } from '@ngrx/core/compose';

import { rootReducer } from './reducers';
import { StoreDevToolsModule } from './features/store-devtools.module';

import { localStorageSync } from 'ngrx-store-localstorage';
export const APP_IMPORTS = [
...
  // StoreModule.provideStore(rootReducer),
    StoreModule.provideStore(
      compose(
          localStorageSync(['finder, auth']),
          combineReducers
      )(rootReducer)
  ),
...
]
```

Unfortunately after this, my reducer state isn't available at all.

Does somebody have an idea?

**Comment by Matmo10** [comment]
I've got it to work by doing this:

```
StoreModule.provideStore(compose(
            localStorageSync(['filters'], true),
            combineReducers
            )(reducers)
        )
```

But I had to comment out all the helpful/extra stuff in /reducers/index.ts

I'm also struggling to figure out how to configure this right to also work with AOT since the documentation is lacking.

**Comment by Matmo10** [comment]
I think I figured it out actually. For dev environment, I added it to DEV_REDUCERS:

`const DEV_REDUCERS = [stateSetter, storeFreeze, localStorageSync(['yourReducer'], true)];`

and for prod, I changed productionReducer to the following:

`const productionReducer = compose(localStorageSync(['yourReducer'], true), combineReducers)(reducers);`

You can create a PROD_REDUCERS array if you want to follow the DEV_REDUCERS pattern but this seems to be working for me.

**Comment by qdouble** [comment]
I may or may not add it on later on, I'm trying to keep this repo based around stuff that I use as it will be easier for me to make sure everything is working right and support it. I'm not currently using it in any of my projects, so wouldn't be quite sure of the best practices or limitations of using it.  

@smith64fx @Matmo10 if either you come up with a good way for it to work, maybe we can add instructions to the wiki?
